import * as Assert from 'node:assert/strict'
import * as Fs from 'node:fs'
import * as Os from 'node:os'
import * as Path from 'node:path'
import test from 'node:test'
import { cleanVersionFromTagRef, runVersioning } from '../sources/versioning.js'

const PackageName = 'online-dsl-forge'
const ParserPackageName = 'online-dsl-forge-parser'
const SemaPackageName = 'online-dsl-forge-sema'

type Workspace = {
  root: string
  manifestPath: string
  lockfilePath: string
}

function createWorkspace(manifestVersion = '0.0.0', lockVersion = '0.0.0'): Workspace {
  const root = Fs.mkdtempSync(Path.join(Os.tmpdir(), 'online-dsl-forge-versioning-'))
  const sourceDir = Path.join(root, 'source')
  Fs.mkdirSync(sourceDir)

  const manifestPath = Path.join(sourceDir, 'Cargo.toml')
  const lockfilePath = Path.join(root, 'Cargo.lock')

  Fs.writeFileSync(
    manifestPath,
    `[package]
name = "${PackageName}"
version = "${manifestVersion}"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
description = "A bounded parser and runtime for in-memory DSL expressions."
repository = "https://github.com/OxiBelt/online-dsl-forge"
publish = false

[dependencies]
serde = "1.0.228"
`
  )

  Fs.writeFileSync(
    lockfilePath,
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${PackageName}"
version = "${lockVersion}"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "placeholder"
`
  )

  return { root, manifestPath, lockfilePath }
}

function createSplitWorkspace(manifestVersion = '0.0.0', lockVersion = '0.0.0'): Workspace {
  const root = Fs.mkdtempSync(Path.join(Os.tmpdir(), 'online-dsl-forge-versioning-'))
  const parserDir = Path.join(root, 'parser')
  const semaDir = Path.join(root, 'sema')
  const sourceDir = Path.join(root, 'source')
  Fs.mkdirSync(parserDir)
  Fs.mkdirSync(semaDir)
  Fs.mkdirSync(sourceDir)

  const parserManifestPath = Path.join(parserDir, 'Cargo.toml')
  const semaManifestPath = Path.join(semaDir, 'Cargo.toml')
  const manifestPath = Path.join(sourceDir, 'Cargo.toml')
  const lockfilePath = Path.join(root, 'Cargo.lock')

  Fs.writeFileSync(
    parserManifestPath,
    `[package]
name = "${ParserPackageName}"
version = "${manifestVersion}"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
description = "Parser crate."
repository = "https://github.com/OxiBelt/online-dsl-forge"
publish = false

[dependencies]
serde = "1.0.228"
`
  )

  Fs.writeFileSync(
    semaManifestPath,
    `[package]
name = "${SemaPackageName}"
version = "${manifestVersion}"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
description = "Semantic analysis crate."
repository = "https://github.com/OxiBelt/online-dsl-forge"
publish = false

[dependencies]
online-dsl-forge-parser = { path = "../parser", version = "${manifestVersion}" }
serde = "1.0.228"
`
  )

  Fs.writeFileSync(
    manifestPath,
    `[package]
name = "${PackageName}"
version = "${manifestVersion}"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
description = "A bounded parser and runtime for in-memory DSL expressions."
repository = "https://github.com/OxiBelt/online-dsl-forge"
publish = false

[dependencies]
online-dsl-forge-parser = { path = "../parser", version = "${manifestVersion}" }
online-dsl-forge-sema = { path = "../sema", version = "${manifestVersion}" }
serde = "1.0.228"
`
  )

  Fs.writeFileSync(
    lockfilePath,
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${PackageName}"
version = "${lockVersion}"
dependencies = [
 "${ParserPackageName}",
 "${SemaPackageName}",
 "serde",
]

[[package]]
name = "${ParserPackageName}"
version = "${lockVersion}"
dependencies = [
 "serde",
]

[[package]]
name = "${SemaPackageName}"
version = "${lockVersion}"
dependencies = [
 "${ParserPackageName}",
 "serde",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "placeholder"
`
  )

  return { root, manifestPath, lockfilePath }
}

function cleanup(workspace: Workspace): void {
  Fs.rmSync(workspace.root, { force: true, recursive: true })
}

test('cleans stable and prerelease tag refs', () => {
  Assert.equal(cleanVersionFromTagRef('refs/tags/v1.2.3'), '1.2.3')
  Assert.equal(cleanVersionFromTagRef('refs/tags/1.2.3'), '1.2.3')
  Assert.equal(cleanVersionFromTagRef('refs/tags/v1.2.3-beta.1'), '1.2.3-beta.1')
})

test('rejects non-tag and build metadata refs', () => {
  Assert.throws(() => cleanVersionFromTagRef('refs/heads/main'), /refs\/tags/)
  Assert.throws(() => cleanVersionFromTagRef('refs/tags/v1.2.3+build.4'), /build metadata/)
})

test('check mode accepts committed placeholder versions', t => {
  const workspace = createWorkspace()
  t.after(() => cleanup(workspace))

  const result = runVersioning({
    workspacePath: workspace.root,
    manifestPath: 'source/Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    releasePublish: false
  })

  Assert.deepEqual(result, {
    mode: 'check',
    packageName: PackageName,
    version: '0.0.0'
  })
})

test('check mode accepts committed placeholder versions for a package set', t => {
  const workspace = createSplitWorkspace()
  t.after(() => cleanup(workspace))

  const result = runVersioning({
    workspacePath: workspace.root,
    lockfilePath: 'Cargo.lock',
    packages: [
      { packageName: ParserPackageName, manifestPath: 'parser/Cargo.toml' },
      { packageName: SemaPackageName, manifestPath: 'sema/Cargo.toml' },
      { packageName: PackageName, manifestPath: 'source/Cargo.toml' }
    ],
    releasePublish: false
  })

  Assert.deepEqual(result, {
    mode: 'check',
    packageName: `${ParserPackageName},${SemaPackageName},${PackageName}`,
    version: '0.0.0'
  })
})

test('check mode rejects committed non-placeholder manifest version', t => {
  const workspace = createWorkspace('1.2.3')
  t.after(() => cleanup(workspace))

  Assert.throws(
    () => runVersioning({
      workspacePath: workspace.root,
      manifestPath: 'source/Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /package version must be 0\.0\.0/
  )
})

test('check mode rejects committed non-placeholder lockfile version', t => {
  const workspace = createWorkspace('0.0.0', '1.2.3')
  t.after(() => cleanup(workspace))

  Assert.throws(
    () => runVersioning({
      workspacePath: workspace.root,
      manifestPath: 'source/Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /Cargo\.lock online-dsl-forge version must be 0\.0\.0/
  )
})

test('release mode applies tag version and removes publish lock', t => {
  const workspace = createWorkspace()
  t.after(() => cleanup(workspace))

  const result = runVersioning({
    ref: 'refs/tags/v1.2.3-beta.1',
    workspacePath: workspace.root,
    manifestPath: 'source/Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    releasePublish: true
  })

  const manifest = Fs.readFileSync(workspace.manifestPath, 'utf8')
  const lockfile = Fs.readFileSync(workspace.lockfilePath, 'utf8')

  Assert.equal(result.version, '1.2.3-beta.1')
  Assert.match(manifest, /^version = "1\.2\.3-beta\.1"$/m)
  Assert.doesNotMatch(manifest, /^publish\s*=\s*false$/m)
  Assert.match(lockfile, /^version = "1\.2\.3-beta\.1"$/m)
})

test('release mode applies tag version to package set and local dependencies', t => {
  const workspace = createSplitWorkspace()
  t.after(() => cleanup(workspace))

  const result = runVersioning({
    ref: 'refs/tags/v1.2.3-beta.1',
    workspacePath: workspace.root,
    lockfilePath: 'Cargo.lock',
    packages: [
      { packageName: ParserPackageName, manifestPath: 'parser/Cargo.toml' },
      { packageName: SemaPackageName, manifestPath: 'sema/Cargo.toml' },
      { packageName: PackageName, manifestPath: 'source/Cargo.toml' }
    ],
    releasePublish: true
  })

  const parserManifest = Fs.readFileSync(Path.join(workspace.root, 'parser/Cargo.toml'), 'utf8')
  const semaManifest = Fs.readFileSync(Path.join(workspace.root, 'sema/Cargo.toml'), 'utf8')
  const manifest = Fs.readFileSync(workspace.manifestPath, 'utf8')
  const lockfile = Fs.readFileSync(workspace.lockfilePath, 'utf8')

  Assert.equal(result.version, '1.2.3-beta.1')
  Assert.match(parserManifest, /^version = "1\.2\.3-beta\.1"$/m)
  Assert.doesNotMatch(parserManifest, /^publish\s*=\s*false$/m)
  Assert.match(semaManifest, /^version = "1\.2\.3-beta\.1"$/m)
  Assert.match(
    semaManifest,
    /^online-dsl-forge-parser = \{ path = "\.\.\/parser", version = "1\.2\.3-beta\.1" \}$/m
  )
  Assert.doesNotMatch(semaManifest, /^publish\s*=\s*false$/m)
  Assert.match(manifest, /^version = "1\.2\.3-beta\.1"$/m)
  Assert.match(
    manifest,
    /^online-dsl-forge-parser = \{ path = "\.\.\/parser", version = "1\.2\.3-beta\.1" \}$/m
  )
  Assert.match(
    manifest,
    /^online-dsl-forge-sema = \{ path = "\.\.\/sema", version = "1\.2\.3-beta\.1" \}$/m
  )
  Assert.doesNotMatch(manifest, /^publish\s*=\s*false$/m)
  Assert.equal((lockfile.match(/^version = "1\.2\.3-beta\.1"$/gm) ?? []).length, 3)
})

test('release mode requires a tag ref', t => {
  const workspace = createWorkspace()
  t.after(() => cleanup(workspace))

  Assert.throws(
    () => runVersioning({
      workspacePath: workspace.root,
      manifestPath: 'source/Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: true
    }),
    /requires --ref/
  )
})

test('release mode rejects an unexpected package name', t => {
  const workspace = createWorkspace()
  t.after(() => cleanup(workspace))

  Assert.throws(
    () => runVersioning({
      ref: 'refs/tags/v1.2.3',
      workspacePath: workspace.root,
      manifestPath: 'source/Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: 'other-package',
      releasePublish: true
    }),
    /package name must be other-package/
  )
})
